require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - "bin/*"
    - "config/initializers/*"
    - "db/migrate/20241025140309_create_active_storage_tables.active_storage.rb"
    - "db/migrate/20241025140309_create_active_storage_tables.active_storage.rb"

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/schema.rb"

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"